/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Taller3;

import Taller3.Punto3.Cola;
import Taller3.Punto3.PilaConColas;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    }

}
